### PR TITLE
Review

### PR DESCRIPTION
**Pull request by scott-wilson**

### CODE REVIEW

**Comment by MrHedmad** [comment]
Hey! Thanks a lot for the PR! I know it's still a draft, but I wanted to ask a few questions, if you could take the time to answer:
- Did you use `rust fmt` to format the code? I use it too but I haven't setup a pre-commit hook yet, therefore some parts of the code might be not properly formatted. I think that the changes in formatting are due to that?
- Is `impl AsRef<Path>` always preferred to `PathBuf` or `Path`? Are there reasons to not use them?
- What's the difference between `Into<PathBuf>` and `AsRef<Path>`, in practical terms? I don't really get what `AsRef` differs from `Into` or `From`...
- I have a lot of useless calls around (i.e. stray `.as_str()`, etc...). Is that something that `clippy` could fix?
- I know of the implications of calls to `.into_string_lossy()`, but "in modern times", say, how risky is it to call a lossy function? I don't think I have ever seen files that are not UTF-8 nowadays, let alone paths.
- Sometimes the compiler complains that I've passed `Something` instead of `&Something`. I thought that it would handle that automatically, i.e. converting to reference if the value need not be borrowed.

Thank you so much again for the review, and thank you in advance if you do take the time to answer me!

**Comment by scott-wilson** [comment]
Gladly! I've mostly marked this as a draft, since it is supposed to be used as a learning piece vs an actual contribution.

- I have my editor automatically run a formatter on save. So, some of the changes are likely due to that. If that adds confusion, I can manually fix that.
- Depends. If this is an API function, then allowing more liberal inputs can be nice. This way you can do something like `do_thing_with_path("/path/to/thing")` or `do_thing_with_path(PathBuf::from("/path/to/thing"))`. However, generics add to compile time. It may be a good idea to use generics on the API functions, but the inner functions use either `&Path` or `PathBuf`, depending on what you need to do (likely `&Path`).
- The difference is that one will cast the value to a reference and may not allocate, while the other will likely allocate. So, use `AsRef<Path>` when you just want to get a reference to the value, and `Into<Path>` when you want to own it, and you're okay with paying whatever allocation cost.
- I'm not sure. Safest thing to do would be to finish up your work, commit it, then run `cargo clippy --fix` and see what happens.
- It **should** be safe, but no promises. I believe the way Path/PathBuf is structured is based around the idea of "this is the implementation that should work for all supported platforms". There's some crates that'll make it so you'll only ever deal with utf-8 paths.
- Rust is all about being explicit because it wants to prevent a whole host of possible bugs. So, in this case, I'd treat it less of the compiler is complaining and more of the compiler is trying to be a buddy and helping you prevent bugs.

**Comment by MrHedmad** [comment]
Thanks for replying! I'll incorporate the `AsRef<Path>` in my calls as I think it's the most useful and immediate change I can make. I feel that I lack knowledge on what can/cannot be cast in the different types, and the traits that govern these changes. I'm also not really caring about borrowing/ownership, so I just call `to_owned()` wherever. I'll work on it! 

Thanks for the suggestions and your time. I hope you don't complain if I manually add some of the edits in!

**Comment by scott-wilson** [comment]
Go for it! As for what can/can't be cast, sometimes you can find out by
looking at the docs for the type. Some things are tricky, because you can
have traits that are automatically added based on if you implement a trait
(for example, implementing `From<X> for Y` will automatically implement
`Into<Y> for X`.

**Comment by MrHedmad** [comment]
Hey! Do you mind if I close this PR? It was really useful and I'll refer to it again, but every time that I see "1 PR" i forget that it was this one :D

**Comment by scott-wilson** [comment]
No worries! I'll close.

**Pull request closed without merging**
